blog/urls.py
from django.conf.urls import patterns,url
from blog import views

urlpatterns = patterns('', url(r'^$', views.index, name='index'),
	                       url(r'^contact/$', views.contact, name='contact'),)

halkemi/urls.py
from django.conf.urls import patterns,url
from halkemi import views


urlpatterns = patterns('', url(r'^$', views.index, name='index'),
                           url(r'^signup$', views.signup, name='signup'),
                           url(r'^login$', views.signin, name='login'),
                           url(r'^signout$', views.signout, name='signout'),
                           url(r'^profile$', views.profile, name='profile'),
                           url(r'^edit-profile$', views.edit_profile, name='edit-profile'),
                           url(r'^edit-profile-picture$', views.edit_profile_picture, name='edit-profile-picture'),)

halkemy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'halkemy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^halkemi/', include('halkemi.urls', namespace="halkemi")),
    )

halkemi/models/category.py
from django.db import models

class Category(models.Model):
	choice = (('fashion', 'fashion'),
              ('food', 'food'),
              ('art & photography', 'art & phoyography'),)

	category_name = models.CharField(max_length=100, choices=choice)
	created_at = models.DateTimeField()
	updated_at = models.DateTimeField() 


	class Meta:
		db_table = 'hali_db_category'

	def __unicode__(self):
		return self.category_name

halkemi/models/content.py
from django.db import models
from halkemi.models.category import Category
from django.contrib.auth.models import User

class Content(models.Model):

	user_id = models.ForeignKey(User)
	category = models.ForeignKey(Category)
	content = models.TextField()
	pic_link = models.TextField()
	created_at = models.DateTimeField()
	updated_at = models.DateTimeField()

	class Meta:
		db_table = 'hali_db_content'

	def __unicode__(self):
		return self.content

halkemi/models/user.py
from django.db import models
from django.contrib.auth.models import User

class User(models.Model):
	user = models.OneToOneField(User)
	skill = models.CharField(max_length=100)
	description = models.TextField()
	profile_pic = models.TextField()
	pic_small = models.TextField()

	class Meta:
		db_table = 'hali_db_user'

	def __unicode__(self):
		return self.skill

halkemi/forms.py
from django import forms
from django.core import validators
from halkemi import validator

class SignUpForm(forms.Form):
	
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
	                                                         'id':'login-username',
	                                                         'placeholder':'Username'}), max_length=30,
	                                                         validators=[validators.validate_slug,
	                                                         validator.is_unique_username])

	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control',
	                                                        'id':'login-username',
	                                                        'placeholder':'Email'}),
	                                                        validators=[validators.validate_email,
	                                                        validator.is_unique_email])
    
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
	                                                         'id':'login-username',	                                                       
	                                                         'placeholder':'First Name'}), max_length=30)

	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
	                                                         'id':'login-username',	                                                       
	                                                         'placeholder':'Last Name'}), max_length=30)


	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',
	                                                         'id':'login-password',
	                                                         'name':'password',
	                                                         'placeholder':'Password'}))

	vpassword = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',
	                                                         'id':'login-password',
	                                                         'name':'password',
	                                                         'placeholder':'Retype Password'}))


	def clean(self):
		cleaned_data = super(SignUpForm, self).clean()
		password = cleaned_data.get('password')
		vpassword = cleaned_data.get('vpassword')

		if password and vpassword:
			if password != vpassword:
				msg = "retype password must be equal to password"
				self.add_error('vpassword', msg)


class LoginForm(forms.Form):

	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
	                                                        'id':'login-username',
	                                                        'name':'username',
	                                                        'placeholder':'Username'}),)

	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',
	                                                         'id':'login-password',
	                                                         'name':'password',
	                                                         'placeholder':'Password'}),)

class EditProfileForm(forms.Form):

	skill = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
		                                                 'id':'Name',
		                                                 'name':'skill',
		                                                 'placeholder':'Skill'}), max_length=30)

	description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control',
		                                                      'id':'contact-message',		                                                      
		                                                      'name':'description',
		                                                      'placeholder':'Description'}), max_length=200)

	                                                        
class EditProfilePicForm(forms.Form):

	profile_pic = forms.ImageField()



halkemi/views.py
from django.shortcuts import render,redirect
from halkemi.forms import SignUpForm, LoginForm, EditProfileForm 
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout

def index(request):
	return render(request, 'halkemi/index.html');


def signup(request):

	if request.method == 'POST':
		signup_form = SignUpForm(request.POST)
		if signup_form.is_valid():
			user = User()
			user.username = signup_form.cleaned_data['username']
			user.email = signup_form.cleaned_data['email']
			user.first_name = signup_form.cleaned_data['first_name']
			user.last_name = signup_form.cleaned_data['last_name']
			user.set_password(signup_form.cleaned_data['password'])
			user.save()
				
			return redirect(reverse('halkemi:login'))			
		else:
			return render(request, 'halkemi/signup.html', {'form':signup_form, 'message':'Please fill the form again'})
	    
	elif request.method == 'GET':
		signup_form = SignUpForm(auto_id=False)

		return render(request, 'halkemi/signup.html', {'form':signup_form})

def signin(request):

	if request.method == 'POST':
		login_form = LoginForm(request.POST)
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect(reverse('halkemi:profile'))
		else:
			return render(request, 'halkemi/login.html',{'form':login_form,'message':'invalid email address or password'})

	elif request.method == 'GET':
		login_form = LoginForm(auto_id=False)

		return render(request, 'halkemi/login.html', {'form': login_form})

def signout(request):
	logout(request)
	return redirect(reverse('halkemi:index'))

def profile(request):
	if request.method == "GET":
		return render(request, 'halkemi/profile.html')

def edit_profile(request):
	form = EditProfileForm(auto_id=False)
	if request.method == 'GET':
		return render(request, 'halkemi/edit_profile.html', {'form':form})

	elif request.method == 'POST':
		form = EditProfileForm(request.POST)
		if form.is_valid():
			pass
		else:
			return render(request, 'halkemi/edit_profile.html', {'form':form, 'message': 'Please retype the fields'})

def edit_profile_picture(request):
	pass

halkemi/templates/halkemi/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <title>halkemy | {% block title%}{% endblock %}</title>
        <meta name="description" content=""/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>

        <link rel="stylesheet" href="{% static "halkemi/css/bootstrap.min.css" %}"/>
        <link rel="stylesheet" href="{% static "halkemi/css/icomoon-social.css" %}"/>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="{% static "halkemi/css/leaflet.css" %}" />
		<!--[if lte IE 8]>
		    <link rel="stylesheet" href="css/leaflet.ie.css" />
		<![endif]-->
		<link rel="stylesheet" href="{% static "halkemi/css/main.css" %}"/>

        <script src="{% static "halkemi/js/modernizr-2.6.2-respond-1.1.0.min.js" %}"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

<!-- Navigation & Logo-->
        <div class="mainmenu-wrapper">
            <div class="container">
            
        <!-- if logged in, hide this -->  
 
            <!--check if user is logged in-->
            {% if user.is_authenticated %}
             
            <div class="menuextras">
                <div class="extras">
                        <ul>
                            <li><a href="{% url 'halkemi:profile' %}" class="btn btn-blue"><span class="glyphicon glyphicon-user icon-white"> Profile</a></li>                          
                            <li><a href="{% url 'halkemi:signout' %}" class="btn btn-blue">Signout</a></li>
                            
                        </ul>
                    <div class="btn-group">
                       <a class="btn btn-blue  dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-cog icon-white">  Account <span class="caret"></span> </a>
                       <ul class="dropdown-menu">
                          <li><a href="delete_account_conf.php">Delete Account</a></li>
                          <li><a href="change_password.php">Change Password</a></li>
                          <li><a href="edit_info.php">Edit Information</a></li>
                       </ul>
                    </div>
               </div>
            </div>
                   
            {% else %}

                <div class="menuextras">
                    <div class="extras">
                        <ul>
                            <li><a href="{%url 'halkemi:signup'%}" class="btn btn-blue">Register</a></li>
                            <li><a href="{% url 'halkemi:login'%}" class="btn btn-blue">Login</a></li>
                        </ul>
                    </div>
                </div>
                
            {% endif %}  <!--end of if-->
      
                <nav id="mainmenu" class="mainmenu">
                    <ul>
                        <li class="logo-wrapper"><a href="index.html"><img src="{% static "halkemi/halkemy7.jpg" %}"/></a></li>
                        <li>
                            <a href="{% url 'halkemi:index' %}"><span class="glyphicon glyphicon-home icon-white"> HOME</a>
                        </li>
                        <li>
                            <a href="gallery.php"><span class="glyphicon glyphicon-picture"> GALLERY</a>
                        </li>
                        <li>
                            <a href="about_us.php">ABOUT</a>
                            
                        </li>
                        
                    </ul>
                </nav>
            </div>
        </div>
<!-- End of Navigation -->

      {% block body %} {% endblock %}
            
<!-- Footer -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    
                    <div class="col-footer col-md-6 col-xs-6">
                        <h3>Navigate</h3>
                        <ul class="no-list-style footer-navigate-section">
                            <li><a href="index.php">HOME</a></li>
                            <li><a href="gallery.php">GALLERY</a></li>
                            <li><a href="about_us.php">ABOUT US</a></li>
                            <li><a href="contact_us.php">CONTACT US</a></li>
                            <li><a href="#">OUR TEAM</a></li>
                        </ul>
                    </div>
                    
                    <div class="col-footer col-md-6 col-xs-6">
                        <h3>Contacts</h3>
                        <p class="contact-us-details">
                            <b>Address: </b>Ibadan<br/>
                            <b>Mobile 1: </b>08068247687<br/>
                            <b>Mobile 2: </b>08038619121<br/>
                            <b>Email: </b> <a href="mailto:contactus@halkemy.com">contactus@halkemy.com</a>
                        </p>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="footer-copyright">&copy; 2014 Halkemy. All rights reserved.</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Javascripts -->
       
        <script src="{% static "halkemi/js/jquery1.js" %}"></script>            
        <script src="{% static "halkemi/js/bootstrap.min.js" %}"></script>
        <script src="{% static "halkemi/js/jquery.masonry.min.js" %}"></script>
        <script src="{% static "halkemi/js/base.js" %}"></script>
        <script src="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js"></script>
        <script src="{% static "halkemi/js/jquery.fitvids.js" %}"></script>
        <script src="{% static "halkemi/js/jquery.sequence-min.js" %}"></script>
        <script src="{% static "halkemi/js/jquery.bxslider.js" %}"></script>
        <script src="{% static "halkmemi/js/main-menu.js" %}"></script>
        <script src="{% static "halkemi/js/template.js" %}"></script>        
    </body>
</html>        

halkemi/templates/halkemi/edit_profile.html
{% extends "halkemi/base.html"%}

{% block title%} Edit Profile{% endblock %}

{% block body%}
     <div class="section section-breadcrumbs">
        <div class="container">
    		<div class="row">
	    		<div class="col-md-2">
	    			<h1>Edit profile</h1>                   
				</div>
                 <a href="{%url 'halkemi:profile'%}" class="btn btn-blue">Profile</a>
			</div>
		</div>
	</div>
     
     <div class="section">
	    	<div class="container">
	        	<div class="row">

	        		{% if message%}
                       <div class="alert alert-success">
                       	 {{message}}
                       </div>
	        		{% endif %}
                <!-- edit picture form -->
	        		<div class="col-md-4">
                     <div class="product-image-large">
	    		      	  <img src="" alt="user pics" />
	    	    	   </div>
                       
                      <div class="contact-form-wrapper">
                       <form method='post' action="{% url 'halkemi:edit-profile'%}" enctype="multipart/form-data"> 
                            {% csrf_token %}
                        <div class="form-group {% if form.profile_pic.errors %} has-error {%endif%}">
		        			<label for="Name" class="col-sm-3 control-label"><b>Change picture</b></label>
		        		 	<div class="col-sm-9">
							<input class="form-control" id="Name" type="file" name="profile_pic" >                            
						     </div>
                            {% if form.profile_pic.errors %}
                                {% for error in form.profile_pic.errors %}
                                   <p class="text-danger">{{error|escape}}</p>
                                {% endfor %}
                            {% endif %}
						</div>
                        <div class="form-group">
						   <div class="col-sm-12">
							<button type="submit" class="btn pull-right">Upload</button>
							</div>
						</div>
                        </form>
                      
                      </div> 

                     </div>
                    <!-- End --> 
	        		<div class="col-md-8">
	        			<!-- Edit profile form-->
	        			<h3>Edit your profile</h3>

	        			<div class="contact-form-wrapper">                              
                             <form method="POST" action="{% url 'halkemi:edit-profile'%}"   class="form-horizontal" role="form">
                             	 {% csrf_token %}
                                <div class="form-group {%if form.skill.errors%}has-error{%endif%}">                                    
		        				 	<label for="Skill" class="col-sm-3 control-label"><b>Skill</b></label>
		        				 	<div class="col-sm-9">
										{{form.skill}}
									</div>
									{% if form.skill.errors%}
                                      {%for error in form.skill.errors%}
									   <p class="text-danger"> {{error|escape}}</p>
									  {%endfor%}
									{%endif%}
								</div>
                                  			
								<div class="form-group {%if form.description.errors%} has-error {%endif%}">
									<label for="contact-message" class="col-sm-3 control-label"><b>User description</b></label>
									<div class="col-sm-9">
										{{form.description}}
									</div>
									{%if form.description.errors%}
									   {%for error in form.description.errors%}
                                          <p class="text-danger">{{error|escape}}</p>
                                       {%endfor%}
									{%endif%}
								</div>

								<div class="form-group">
									<div class="col-sm-12">
										<button type="submit" class="btn pull-right">Edit</button>
									</div>
								</div>
		        			</form>
		        		</div>
		        		<!-- End  -->

	        		</div>
	        	</div>
	    	</div>
	    </div>
  
{% endblock %}        

halkemi/templates/halkemi/index.html
{% extends "halkemi/base.html" %}  <!-- this file extends the base file -->

{% block title %} Home {% endblock%}

{% block body %}   <!--start of the section that is injected in base.blade.php-->
 <!-- Homepage Slider -->
        <div class="homepage-slider">
        	<div id="sequence">
				<ul class="sequence-canvas">
					<!-- Slide 1 -->
					<li class="bg4">
                      
						<!-- Slide Title -->
						<h2 class="title">Welcome to Halkemy!</h2>
						<!-- Slide Text -->
						<h3 class="subtitle">Halkemy is a new platform for promoting Creativity</h3>
					 							
					</li>
					<!-- End Slide 1 -->
					<!-- Slide 2 -->
					<li class="bg3">
						<!-- Slide Title -->
						<h2 class="title">Be Creative!</h2>
						<!-- Slide Text -->
						<h3 class="subtitle">The site is aimed at exhibiting the creativity of individuals.</h3>
						
					</li>
					<!-- End Slide 2 -->
					<!-- Slide 3 -->
					<li class="bg1">
						<!-- Slide Title -->
						<h2 class="title">Join and explore!</h2>
						<!-- Slide Text -->
						<h3 class="subtitle">View the creative works of individuals and also display yours</h3>
						
					</li>
					<!-- End Slide 3 -->
				</ul>
				<div class="sequence-pagination-wrapper">
					<ul class="sequence-pagination">
						<li>1</li>
						<li>2</li>
						<li>3</li>
					</ul>
				</div>
			</div>
        </div>
        <!-- End Homepage Slider -->			

		<!-- features bar -->
	    <div class="section section-white">
			<div class="container">
            <div class="row">
            <div class="col-md-6 col-md-offset-5">
			<h1>Features</h1>
            </div>
            </div>	
	    	</div>
		</div>
		<!-- End of features bar -->

{% endblock %}	<!-- end of the section-->

halkemi/templates/halkemi/login.html
{% extends "halkemi/base.html" %}

{% block title %}Login{% endblock %}

{% block body %}
<!-- pop up -->
   <div class="modal fade bs-exam-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
     <div class="modal-dialog modal-sm">
       <div class="modal-content">
       
       <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Are you sure you want to reset your password</h4>
       
        
      
        <a href="reset_password.php" class="btn btn-default" > Yes </a>
        <a class="btn btn-primary" data-dismiss="modal"> No </a>
      </div>
      
      </div> 
     </div>
  </div>
    <!-- End -->
      

<!-- Log in -->

    <div class="section section-breadcrumbs">
        <div class="container">
    		<div class="row">
	    		<div class="col-md-12">
	    			<h1>Login</h1>
				</div>
			</div>
		</div>
	</div>
     <!-- login form --> 
        <div class="section">
	    	<div class="container">
				<div class="row">
                    {% if message%}
                          <div class="alert alert-danger">
                            {{message}}
                          </div>
                    {% endif %}  
					<div class="col-sm-5">
						<div class="basic-login">

							<form method="post" action="{% url 'halkemi:login'%}" role="form">
								{% csrf_token %}
								<div class="form-group">
								    <label for="login-username"><i class="icon-user"></i> <b>Username</b></label>
                                    {{form.username}}
								</div>
								<div class="form-group">
									<label for="login-password"><b>Password</b></label>
		        				 	{{form.password}}
								</div>
								<div class="form-group">									
									<a class="forgot-password" data-toggle="modal" data-target=".bs-exam-modal-sm">Forgot password?</a>
									<button type="submit" class="btn pull-right" >Login</button>
									<div class="clearfix"></div>
								</div>
							</form>
						</div>

					</div>
				
				</div>
			</div>
		</div>
    <!-- end -->   

{% endblock %}

halkemi/templates/halkemi/profile.html
{% extends "halkemi/base.html" %}

{% block title %}Profile{% endblock %}        
 
{% block body%}
       	<!-- user header -->
        <div class="section">
          <div class="container">
            <div class="row">
              <div class="col-md-4">
                  <div class="product-image-large">
	    			<img src= ""  alt="picture"/>
	    	    	</div>
                </div>
                
                <div class="col-md-6">
                    <table class="jobs-list">
	    					<tr>
	    						<th><span class="glyphicon glyphicon-user"></span>Username: {{user.username}}</th>
    						
	    					</tr>
	    					<tr>
	    						<!-- Position -->
	    						<td class="job-position">
	    						   <b>Skill:</b>  
	    						</td>
	    							    						
	    					</tr>

	    					<tr>
	    						<td class="job-position">
  							      <b>About me: </b><p class="profile"></p> 
	    						</td>	    						
	    					</tr>
	    				</table>
	    			</div>


                </div>
              </div>
            </div>
          
        <!-- End of user header -->
        
        <!-- User navigation -->
    <div class="section section-breadcrumbs">
        <div class="container">
    		<div class="row">
	    		<div class="col-xs-6 col-md-2">
	    		<a href="{% url 'halkemi:edit-profile'%}" class="btn btn-blue">Edit profile</a>	
				</div>
                <div class="col-xs-6 col-md-2">
	    		<a href="" class="btn btn-blue">Add your work</a>	
				</div>
                <div class="col-xs-6 col-md-2">
	    		<a href="" class="btn btn-blue">Show work</a>	
				</div>
			</div>
		</div>
	</div>
    
{% endblock %}     

halkemi/templates/halkemi/signup.html
{% extends "halkemi/base.html" %}
<!-- Log in -->

{% block title %}Signup{% endblock %}
 
{% block body %}
     <div class="section section-breadcrumbs">
        <div class="container">
    		<div class="row">
	    		<div class="col-md-12">
	    			<h1>Signup</h1>
				</div>
			</div>
		</div>
	</div>
        
        <div class="section">
	    	<div class="container">
				<div class="row">
				 {% if message %}
                   <div class="alert alert-success">
                       {{message}}
                   </div>
                 {% endif %}	
                 <div class="col-sm-6 col-sm-offset-1 social-login">
						<p>HELLO! To register on this site, you have to be invited.</p>
						<p> The site is still under development(closed beta). If
                           You are interested or have anyone who might be interested,
                           you can <a href="contact_us.php">CONTACT US</a>. </p>
					</div>
				
					<div class="col-sm-5">
						<div class="basic-login">
							<form method="post" action="{%url 'halkemi:signup'%}" role="form">  
							   {% csrf_token %} 
								<div class="form-group {%if form.username.errors%}has-error {%endif%}">
		        				 	<label for="signup-username"><i class="icon-user"></i> <b>Username</b></label>
									  {{form.username}}
									{% if form.username.errors %}
                                      {%for error in form.username.errors %}
									    <p class="text-danger">{{error|escape}}</p>
									  {%endfor%}  
									{%endif%}
								</div>
                                
                                <div class="form-group {%if form.email.errors%}has-error {%endif%}">
		        				 	<label for="signup-email"><i class="icon-user"></i> <b>Email</b></label>
									     {{form.email}}
								    {% if form.email.errors %}
                                       {% for error in form.email.errors %}
									     <p class="text-danger">{{ error|escape }}</p>
									    {% endfor %}
									{% endif %}
								</div>
                                
                                <div class="form-group {%if form.first_name.errors%}has-error {%endif%}">
		        				 	<label for="signup-firstname"><i class="icon-lock"></i> <b>First Name</b></label>
									   {{form.first_name}}
                                    {%if form.first_name.errors%}
								       {% for error in form.first_name.errors %}
									     <p class="text-danger">{{error|escape}}</p>
									   {%endfor%}
								    {%endif%}
								</div>
                                
                                <div class="form-group {%if form.last_name.errors%}has-error {%endif%}">
		        				 	<label for="signup-lastname"><i class="icon-lock"></i> <b>Last Name</b></label>
									   {{form.last_name}}
                                    {%if form.last_name.errors%}
								       {% for error in form.last_name.errors %}
									     <p class="text-danger">{{error|escape}}</p>
									   {%endfor%}
								    {%endif%}
								</div>
                                
								<div class="form-group {%if form.password.errors%}has-error {%endif%}">
		        				 	<label for="login-password"><i class="icon-lock"></i> <b>Password</b></label>
									   {{form.password}}
								     {%if form.password.errors%}
								       {% for error in form.password.errors %}
									     <p class="text-danger">{{error|escape}}</p>
									   {%endfor%}
								    {%endif%}
								</div>
                                
                                <div class="form-group {%if form.vpassword.errors%}has-error {%endif%}">
		        				 	<label for="login-password"><i class="icon-lock"></i> <b>Password</b></label>
									   {{form.vpassword}}
								     {%if form.vpassword.errors%}
								       {% for error in form.vpassword.errors %}
									     <p class="text-danger">{{error|escape}}</p>
									   {%endfor%}
								    {%endif%}
								</div>
                                
								<div class="form-group">													
									<button type="submit" class="btn pull-right" >Signup</button>
									<div class="clearfix"></div>
								</div>
							</form>
						</div>

					</div>                  
                    
				</div>
			</div>
		</div>
       
{% endblock %}